---
- hosts: all
  become: true
  gather_facts: false
  vars_files:
   - dbparams.yml
  tasks:
   - name: Install required packages
     yum: name={{item}} state=installed
     with_items:
      - httpd
      - php
      - php-mysql

   - name: Start and enable Apache
     service: name=httpd state=started enabled=true

   - name: Copy application files
     copy: src=./src/ dest=/var/www/html

   - name: Configure database access
     template: src=templates/dbvars.php.j2 dest=/var/www/html/dbvars.php
