---
- hosts: localhost
  become: false
  gather_facts: false
  tasks:
   - name: Create an instance in AWS
     ec2:
      aws_access_key: "{{AWS_ACCESS_KEY}}"
      aws_secret_key: "{{AWS_SECRET_KEY}}"
      key_name: akropachev
      instance_type: t2.micro
      image: ami-26ebbc5c
      instance_tags:
        Name: "{{inst_name}}-{{item}}"
        Type: Linux_AWS
      wait: false
      group: default
      exact_count: 1
      count_tag: foo
      vpc_subnet_id: subnet-c86b14e2
      assign_public_ip: yes
      region: us-east-1
     register: ec2
     with_items:
      - web
      - db

   - debug: var=ec2

   - debug: msg="Adding host {{ec2.results[0].instances[0].dns_name}} and {{ec2.results[1].instances[0].dns_name}}"

   - name: Adding Web server to inventiry
     add_host: name={{ec2.results[0].instances[0].dns_name}} group=webservers

   - name: Adding DB server to inventory
   - add_host: name={{ec2.results[1].instances[0].dns_name}} group=dbservers

   - name: Wait for hosts to come up
     wait_for: 
      port: 22
      host: "{{ item }}"
      search_regex: OpenSSH
     delay: 60
     with_items:
      - "{{ec2.results[0].instances[0].dns_name}}"
      - "{{ec2.results[1].instances[0].dns_name}}"

- hosts: all
  become: true
  gather_facts: false
  tasks:
   - name: set hostname
     hostname: name={{inventory_hostname}}

- import_playbook: ansible_dbserver.yml 
- import_playbook: ansible_webserver.yml dbhost={{ec2.results[1].instances[0].dns_name}}

- hosts: localhost
  become: false
  gather_facts: false
  tasks:
   - debug: msg="PHP Demo application has been succesfully installed on {{ec2.instances[0].dns_name}}"
