---
- hosts: webservers
  become: true
  gather_facts: false
  vars_files:
   - dbparams.yml
  tasks:
   - debug: var=dbuser
   - name: Install required packages
     yum: name={{item}} state=installed
     with_items:
      - httpd
      - php
      - php-mysql

   - name: Start and enable Apache
     service: name=httpd state=started enabled=true

   - name: Copy application files
     copy: src=./ dest=/var/www/html

   - name: Configure database access
     template: src=dbvars.php.j2 dest=/var/www/html/dbvars.php

   - name: Configure selinux settings
     command: setsebool -P httpd_can_network_connect=1

